### ISSUE TITLE
Проверять авторизацию не в классе DatabaseManager

### ISSUE THREAD

**Issue by AlphaBeth** [GesuYaro/lab7#1]
Сейчас все методы в DatabaseManager содержат строку userChecker.checkUser(currentUser). Это приводит к двум проблемам:
1. Для обработки одного запроса может проверяться авторизация несколько раз (например, в add будет проверяться доступ для генерации id и для самого добавления)
2. Смешивается ответственность. DatabaseManager должен просто выполнять запросы.
3. Наверное, главное - не для всех команд выполняется проверка авторизации, а по условию должна для всех (кроме, очевидно, логина и регистрации).

**Comment by GesuYaro** [comment]
Перенес проверку пользователя из DatabaseManager в CommandHandler. Теперь пользователь проверяется перед вызовом команды.
